[package]
name = "rpios"
version = "0.1.0"
edition = "2024"

[features]
raspberry_pi_3b = []

[[bin]]
name = "kernel8"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
strip = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0.0"
