[tasks.default]
alias = "build"

[tasks.build]
command = "mv"
args = [
    "./target/aarch64-unknown-none-softfloat/release/kernel8",
    "./target/aarch64-unknown-none-softfloat/release/kernel8.img",
]
dependencies = ["compile"]

[tasks.compile]
command = "cargo"
args = ["build", "--release", "--features", "raspberry_pi_3b"]

[tasks.qemu]
command = "qemu-system-aarch64"
args = [
    "-M",
    "raspi3b",
    "-serial",
    "stdio",
    "-display",
    "none",
    # "-s",
    # "-S",
    "-kernel",
    "target/aarch64-unknown-none-softfloat/release/kernel8.img",
]
dependencies = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]
