[config]
default_to_workspace = false

[tasks.default]
alias = "build"

[tasks.build]
command = "mv"
args = [
    "./target/aarch64-unknown-none/release/kernel",
    "./target/aarch64-unknown-none/release/kernel8.img",
]
dependencies = ["compile"]

[tasks.compile]
command = "cargo"
args = ["build", "--release", "-p", "kernel", "--features", "raspi3b"]

[tasks.qemu]
command = "qemu-system-aarch64"
args = [
    "-M",
    "raspi3b",
    "-serial",
    "stdio",
    "-display",
    "none",
    # "-s",
    # "-S",
    "-kernel",
    "target/aarch64-unknown-none/release/kernel8.img",
]
dependencies = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]
